name: Build CE2Utils

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    runs-on: windows-latest
    name: Build MSYS2
    
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: 'Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        cache: true
        install: 'base-devel mingw-w64-x86_64-toolchain msys/scons mingw64/mingw-w64-x86_64-SDL2 mingw64/mingw-w64-x86_64-python-matplotlib mingw64/mingw-w64-x86_64-swig'
    
    - name: 'Build with Scons'
      shell: msys2 {0}
      run: |
        scons -j 8
    
    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: '**/*.exe'
