name: Build CE2Utils

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build_windows:
    runs-on: windows-latest
    name: Build MSYS2
    
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    
    - name: 'Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        cache: true
        install: 'base-devel mingw-w64-x86_64-toolchain msys/scons mingw64/mingw-w64-x86_64-SDL2 mingw64/mingw-w64-x86_64-python-matplotlib mingw64/mingw-w64-x86_64-swig msys/p7zip'
    
    - name: 'Build with Scons'
      shell: msys2 {0}
      run: |
        scons -j 8 avx=2 rgb10a2=1 buildpkg=main-10bit ce2utils-main-10bit.7z
        scons -j 8 avx=2 buildpkg=main ce2utils-main.7z
        scons -j 8 avx=1 buildpkg=main-noavx2 ce2utils-main-noavx2.7z
        scons -j 8 avx=0 buildpkg=main-noavx ce2utils-main-noavx.7z
    
    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v3
      with:
        name: build-win
        path: |
          ce2utils-main-10bit.7z
          ce2utils-main.7z
          ce2utils-main-noavx2.7z
          ce2utils-main-noavx.7z
  
  
  build_linux:
    runs-on: ubuntu-latest
    name: Build Linux
      
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
      
    - name: 'Install required packages'
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
          packages: swig libsdl2-dev scons
          version: 1.0
      
    - name: 'Build with Scons'
      run: |
        scons -j 8
      
    - name: 'Upload Artifacts'
      uses: actions/upload-artifact@v3
      with:
        name: build-linux
        path: '*'
